spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  cloud:
    discovery:
      enabled: false
  
server:
  port: ${PORT:8089}

eureka:
  client:
    enabled: false

logging:
  level:
    com.tmnhat: INFO 