version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    platform: linux/amd64
    container_name: taskflow-postgres
    environment:
      POSTGRES_DB: taskflow_production
      POSTGRES_USER: taskflow_user
      POSTGRES_PASSWORD: TaskFlow2024@VN
    ports:
      - "5432:5432"
    volumes:
      - postgres_production_data:/var/lib/postgresql/data
      - ./postgres_backup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - taskflow-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskflow_user -d taskflow_production"]
      interval: 30s
      timeout: 10s
      retries: 5

  accounts-service:
    image: tranminnhatdut/taskflow-backend:accounts-service-latest
    platform: linux/amd64
    container_name: taskflow-accounts
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=render
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_USERNAME=taskflow_user
      - SPRING_DATASOURCE_PASSWORD=TaskFlow2024@VN
      - SERVER_PORT=8080
      - NEXT_PUBLIC_ACCOUNTS_API_URL=http://14.225.210.28:8080
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped

  projects-service:
    image: tranminnhatdut/taskflow-backend:projects-service-latest
    container_name: taskflow-projects
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=render
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_USERNAME=taskflow_user
      - SPRING_DATASOURCE_PASSWORD=TaskFlow2024@VN
      - SERVER_PORT=8083
      - NEXT_PUBLIC_PROJECTS_API_URL=http://14.225.210.28:8083
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped

  sprints-service:
    image: tranminnhatdut/taskflow-backend:sprints-service-latest
    platform: linux/amd64
    container_name: taskflow-sprints
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=render
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_USERNAME=taskflow_user
      - SPRING_DATASOURCE_PASSWORD=TaskFlow2024@VN
      - SERVER_PORT=8084
      - NEXT_PUBLIC_SPRINTS_API_URL=http://14.225.210.28:8084
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped

  tasks-service:
    image: tranminnhatdut/taskflow-backend:tasks-service-latest
    platform: linux/amd64
    container_name: taskflow-tasks
    ports:
      - "8085:8085"
    environment:
      - AI_SERVICE_URL=http://ai-service:8088     # hoặc http://14.225.210.28:8088
      - SPRING_PROFILES_ACTIVE=render
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_USERNAME=taskflow_user
      - SPRING_DATASOURCE_PASSWORD=TaskFlow2024@VN
      - SERVER_PORT=8085
      - NEXT_PUBLIC_TASKS_API_URL=http://14.225.210.28:8085
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped

  user-service:
    image: tranminnhatdut/taskflow-backend:user-service-latest
    platform: linux/amd64
    container_name: taskflow-users
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=render
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_USERNAME=taskflow_user
      - SPRING_DATASOURCE_PASSWORD=TaskFlow2024@VN
      - SERVER_PORT=8086
      - NEXT_PUBLIC_USER_API_URL=http://14.225.210.28:8086
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped

  file-service:
    image: tranminnhatdut/taskflow-backend:file-service-latest
    platform: linux/amd64
    container_name: taskflow-files
    ports:
      - "8087:8087"
    environment:
      - SPRING_PROFILES_ACTIVE=render
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_USERNAME=taskflow_user
      - SPRING_DATASOURCE_PASSWORD=TaskFlow2024@VN
      - SERVER_PORT=8087
      - NEXT_PUBLIC_FILE_API_URL=http://14.225.210.28:8087
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped
    volumes:
      - file_uploads:/app/uploads
    user: "0:0"

  ai-service:
    image: tranminnhatdut/taskflow-backend:ai-service-v3
    platform: linux/amd64
    container_name: ai-service
    ports:
      - "8088:8088"
    environment:
      - PORT=8088
      - NEXT_PUBLIC_AI_API_URL=http://14.225.210.28:8088
    networks:
      - taskflow-network
    restart: unless-stopped

  notification-service:
    image: tranminnhatdut/taskflow-backend:notification-service-latest
    platform: linux/amd64
    container_name: taskflow-notifications
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=render
      - DATABASE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/taskflow_production
      - SPRING_DATASOURCE_USERNAME=taskflow_user
      - SPRING_DATASOURCE_PASSWORD=TaskFlow2024@VN
      - SERVER_PORT=8089
      - NEXT_PUBLIC_NOTIFICATION_API_URL=http://14.225.210.28:8089
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - taskflow-network
    restart: unless-stopped

volumes:
  postgres_production_data:
    driver: local
  file_uploads:
    driver: local

networks:
  taskflow-network:
    driver: bridge 