spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
server:
  port: ${PORT:8084}

logging:
  level:
    com.tmnhat: INFO

# Service URLs
projects:
  service:
    url: ${PROJECTS_SERVICE_URL:http://14.225.210.28:8083} 